### ISSUE TITLE
nsync_cv.h

### ISSUE THREAD

**Issue by ElliotHYLee** [sampepose/flownet2-tf#18]
I'm using TF 1.3.0 GPU support on Ubuntu 16.04. CUDA = 8.0, cudnn = 6.0

When I try make all finally, I have nsync_cv.h no such file error. I wonder what's causing this. I understand this repository is for TF1.2.1. But I had it working with 1.3 with the previously posted issue. I just changed my ssd and trying the same step once more. But this looks a new issue or very stupid one. I'd appreciate if you can share a bit of insight.

nvcc -g -std=c++11 -I`python -c "import tensorflow; print(tensorflow.sysconfig.get_include())"` -I"/usr/local/cuda/include" -DGOOGLE_CUDA=1 -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__ -D_GLIBCXX_USE_CXX11_ABI=0 -c src/ops/preprocessing/kernels/data_augmentation.cu.cc -x cu -Xcompiler -fPIC  -o src/ops/build/data_augmentation.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/variant.h:31,
                 from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:23,
                 from src/ops/preprocessing/kernels/data_augmentation.h:4,
                 from src/ops/preprocessing/kernels/data_augmentation.cu.cc:6:
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.
Makefile:62: recipe for target 'preprocessing' failed
make: *** [preprocessing] Error 1

**Comment by ElliotHYLee** [comment]
Update: I found I was using TF 1.4.0. Yet, is there still a way to solve this?

**Comment by etienne87** [comment]
in the end...what did you do?

**Comment by ElliotHYLee** [comment]
I have moved to older TF version. I haven't done it but, I'm thinking to move TF weight vectors to Keras and use it with newer TF and Keras.
